Add entry for did:web method.
w3c-ccg/did-method-registry pull request #58
Opened 2019-09-20 15:38 UTC by dmitrizagidulin

Adding the [`did:web` method](https://github.com/w3c-ccg/did-method-web) (which is now a CCG Work Item, and which has sparked the discussion that led to the DID Rubrics document) to the registry.

2019-09-20 15:46 UTC, msporny requested changes
Overall looks good. Please add a Privacy Considerations section as well, or rename "Security Considerations" to "Security and Privacy Considerations"... and add at least one item to it, like "all resolutions of an identifier are centrally logged, enabling pervasive tracking".

2019-09-20 15:48 UTC, dmitrizagidulin commented
Sure thing.

2019-09-20 16:01 UTC, dmitrizagidulin commented
@msporny Expanded, here: https://github.com/w3c-ccg/did-method-web/pull/1

2019-09-21 06:58 UTC, msporny approved these changes

2019-09-21 06:59 UTC, merged