add more details
w3c-ccg/did-method-registry pull request #59
Opened 2019-10-03 19:55 UTC by DavidRicardoWilde

2019-10-11 14:10 UTC, msporny requested changes
Content looks good, there are merge conflicts, please resolve those so we can pull this in.

2019-10-11 20:32 UTC, davidlehn commented on index.html
> -
Looks like merge changed a bit more than it needed to.

2019-10-11 22:43 UTC, DavidRicardoWilde reviewed
fix conflicts issues

2019-10-12 17:37 UTC, msporny approved these changes

2019-10-12 17:37 UTC, merged