Add did:bid:method
w3c-ccg/did-method-registry pull request #67
Opened 2019-11-04 05:41 UTC by teleinfo-bif

BID provides distributed identifiers and blockchain digital identity services for people, enterprises, devices and digital objects. It aims to build a decentralized, data-secure, privacy-protected and flexible identifier system that addresses trusted connections to people, enterprises, devices and digital objects，enabling the vision of the Internet of Everything and trust ingress with everything.

We create this PR to add [BIF DID protocol Specification](https://github.com/teleinfo-bif/bid/blob/master/doc/en/BIF DID protocol Specification_up.md)

2019-11-11 16:15 UTC, msporny requested changes
There is no security/privacy considerations section. Please add a section describing the security/privacy considerations for your DID Method.

2019-11-12 06:27 UTC, teleinfo-bif commented
hello. I already add a section describing the security/privacy considerations in my DID Method. Please confirm it.

2019-11-13 13:54 UTC, msporny approved these changes

2019-11-13 13:54 UTC, msporny commented
Merge conflicts, please fix before I can merge.

2019-11-14 06:20 UTC, closed without merging