Add did:github
w3c-ccg/did-method-registry pull request #75
Opened 2019-12-11 04:51 UTC by OR13

2020-01-17 04:37 UTC, msporny commented
Hey @OR13, sorry the review took so long. While you link to an operational DID Method with a README.md, it doesn't follow the expectations set out by the DID Core spec. Namely, that you clearly define the syntax for the DID Method, the CRUD operations, and a security and privacy considerations section. If you look at many of the other DID Methods in the registry, they define at least those.

At the same time, your implementation is more complete and helpful, but given that we've been attempting to apply the same requirements to everyone across the board (DID syntax, CRUD ops, security and privacy considerations), please update your DID Method specification to cover at least those items. You could just update the README to include those sections.

The PR also now has conflicts given other merges that have happened to the registry.

2020-01-27 05:17 UTC, gjgd commented
@msporny same comment: https://github.com/w3c-ccg/did-method-registry/pull/76#issuecomment-578594536

2020-02-05 18:15 UTC, msporny requested changes
Please link directly to the spec, otherwise, LGTM, merging after you apply the code suggestion.

2020-02-05 18:15 UTC, msporny commented on index.html
> +          <a href="https://github.com/decentralized-identity/github-did/">GitHub DID Method</a>
```suggestion
          <a href="https://github.com/decentralized-identity/github-did/blob/master/packages/docs/did-method-spec/spec.md">GitHub DID Method</a>
```

2020-02-05 18:16 UTC, msporny commented on index.html
> +          <a href="https://github.com/decentralized-identity/github-did/">GitHub DID Method</a>
Also, please fix merge conflicts if there are any remaining.

2020-02-06 14:06 UTC, msporny commented
Merge conflicts appeared after merging did:elem, please fix and we're good to go.

2020-02-06 14:11 UTC, gjgd commented
done

2020-02-06 14:11 UTC, gjgd commented
done

2020-02-06 15:20 UTC, merged