Add did:elem
w3c-ccg/did-method-registry pull request #76
Opened 2019-12-11 04:58 UTC by OR13

Elem is an independent implementation of the sidetree protocol used by `did:ion`, https://github.com/decentralized-identity/sidetree/blob/master/docs/protocol.md

Elem relies on Ethereum instead of Bitcoin.

2020-01-17 04:40 UTC, msporny submitted a review, later dismissed
The linked DID Method spec doesn't contain the sections required by the DID Core specification. See this comment for more information: https://github.com/w3c-ccg/did-method-registry/pull/75#issuecomment-575461028

2020-01-27 05:14 UTC, gjgd commented
@msporny Solved the conflict and updated the README to contain the did method specification containing the required documentation (did method format + CRUD operations + security considerations). Could you review again?

2020-01-27 05:19 UTC, gjgd commented
fixes https://github.com/decentralized-identity/element/issues/142

2020-02-04 14:17 UTC, gjgd commented
ping @msporny when you get a chance to review ^

2020-02-05 18:18 UTC, msporny requested changes
Please link directly to the DID Method spec. Other than that, LGTM for inclusion into the registry. The documentation is weak and would probably not enable anyone else to implement the method in an interoperable fashion.

2020-02-05 18:18 UTC, msporny commented on index.html
> +        <a href="https://github.com/decentralized-identity/element">ELEM DID Method</a>
```suggestion
        <a href="https://github.com/decentralized-identity/element/blob/master/docs/did-method-spec/spec.md">ELEM DID Method</a>
```

2020-02-05 18:19 UTC, msporny commented on index.html
> +        <a href="https://github.com/decentralized-identity/element">ELEM DID Method</a>
Fix remaining merge conflicts too, please.

2020-02-06 06:13 UTC, gjgd commented
@msporny fixed the link and the conflict

2020-02-06 14:05 UTC, msporny approved these changes

2020-02-06 14:05 UTC, merged