Add Echo DID Method
w3c-ccg/did-method-registry pull request #83
Opened 2020-04-08 11:51 UTC by anzhy-chernyavski

[Echo](https://echo.org/)
This PR adds the [DID method specification](https://github.com/echoprotocol/uni-resolver-driver-did-echo/blob/master/echo_did_specifications.md) to the registry.
Thank you for reviewing.

2020-04-08 17:30 UTC, OR13 commented
@msporny I suggest requesting changes on this based on your feedback for https://github.com/w3c-ccg/did-method-registry/pull/84

2020-04-08 17:31 UTC, OR13 requested changes
Any detail on "Privacy Considerations"? apparently this is a required section of a DID Method Spec, I was not aware of this before.

2020-04-09 10:49 UTC, anzhy-chernyavski commented
@OR13 Thanks for the comments, we added information to "Privacy Considerations" section.

2020-04-09 13:05 UTC, msporny approved these changes

2020-04-09 13:05 UTC, merged